SELECT b.BOOK_ID, a.AUTHOR_NAME, DATE_FORMAT(b.PUBLISHED_DATE, "%Y-%m-%d") as PUBLISHED_DATE
FROM BOOK as b, AUTHOR as a
WHERE b.AUTHOR_ID = a.AUTHOR_ID AND CATEGORY = "경제"
ORDER BY b.PUBLISHED_DATE ASC