-- 코드를 입력하세요
SELECT b.TITLE as "TITLE", b.BOARD_ID as "BOARD_ID", r.REPLY_ID as "REPLY_ID", r.WRITER_ID as "WRITER_ID", r.CONTENTS as "CONTENTS", DATE_FORMAT(r.CREATED_DATE, "%Y-%m-%d") as "CREATED_DATE"
FROM USED_GOODS_BOARD as b, USED_GOODS_REPLY as r
WHERE b.BOARD_ID = r.BOARD_ID
  and b.CREATED_DATE >= "2022-10-01"
  and b.CREATED_DATE < "2022-11-01"
ORDER BY r.CREATED_DATE ASC, b.TITLE ASC;